### ISSUE TITLE
Doesnt automatically closing Bracket and Quote

### ISSUE THREAD

**Issue by barraIhsan** [SPGoding/vscode-datapack-helper-plus#37]
This is a little bit strange, **only** in .mcfunction, the closing bracket and quote don't close automatically. I'm using the latest version of visual studio code and the extension. I'm also already try to set the "Automatic closing brackets" and "Automatic closing quotes" to always
![image](https://user-images.githubusercontent.com/57800056/96366958-1cfb2900-1175-11eb-944e-4ba4fad41230.png)

**Comment by SPGoding** [comment]
This has been reported before in #16, but we couldn't reproduce it. Could you please make sure that the language is set to `mcfunction` in the bottom-right corner of your VS Code when opening a mcfunction file?

**Comment by barraIhsan** [comment]
Oh. It works again. I didn't do anything except downloading the syntax highlighting.

**Comment by MDLC01** [comment]
This happened to me today, and it was fixed after I disabled and re-enabled the extension several times. At some point, the extension created a `.datapack` folder I had never seen before in my project. So I think this problem is related to the extension failing to create the `.datapack` folder and therefore not loading properly.
